[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
    ignore::DeprecationWarning
addopts = --strict-markers
markers =
    smoke: 标记为冒烟测试的测试用例
    regression: 标记为回归测试的测试用例
    collection_value: 音量
    traverse_value: ab测试
    volume_purchase_value: 购买量V2_0_2
    V2_0_2
    V2_0_3
    V2_0_4
    V2_0_5
    待编写
    功能用例编写中
    功能用例已完成
    自动化用例开发中
    自动化用例调试中
    已开发完成
    已废弃


